services:
  - type: web
    name: repopulse-api
    env: node
    plan: starter
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromService:
          name: repopulse-db
          type: postgres
      - key: EXTERNAL_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_OAUTH_CALLBACK_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: repopulse-db
    databaseName: repopulse
    plan: starter
